# **Importing Required Libraries**

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,accuracy_score

# **Read the Dataset**

In [2]:
ds = pd.read_csv("dataset_website.csv")
ds.head

<bound method NDFrame.head of        index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0          1                          -1              1                   1   
1          2                           1              1                   1   
2          3                           1              0                   1   
3          4                           1              0                   1   
4          5                           1              0                  -1   
...      ...                         ...            ...                 ...   
11050  11051                           1             -1                   1   
11051  11052                          -1              1                   1   
11052  11053                           1             -1                   1   
11053  11054                          -1             -1                   1   
11054  11055                          -1             -1                   1   

       having_At_Symb

# **Handling NULL values**

In [3]:
ds.isnull().any()

index                          False
having_IPhaving_IP_Address     False
URLURL_Length                  False
Shortining_Service             False
having_At_Symbol               False
double_slash_redirecting       False
Prefix_Suffix                  False
having_Sub_Domain              False
SSLfinal_State                 False
Domain_registeration_length    False
Favicon                        False
port                           False
HTTPS_token                    False
Request_URL                    False
URL_of_Anchor                  False
Links_in_tags                  False
SFH                            False
Submitting_to_email            False
Abnormal_URL                   False
Redirect                       False
on_mouseover                   False
RightClick                     False
popUpWidnow                    False
Iframe                         False
age_of_domain                  False
DNSRecord                      False
web_traffic                    False
P

# **Splitting the Data (Train & Test)**

In [4]:
x = ds.iloc[:,1:31].values
y = ds.iloc[:,-1].values
print(x,y)

[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)